@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzIzMTM3MzMzZDZhZWYxMTk3MDc0NCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NTg3MDQxOCwiZXhwIjoxNzg2NDc1MjE4fQ.w7aABA_p7s_cWk05-WXLGQKZV35pUEmoDSpYA59SHq4

# GET http://localhost:5000/api/events/

# GET http://localhost:5000/api/registrations

# GET http://localhost:5000/api/events/6a72aaff578648463c5d8df9
# Authorization: Bearer {{token}}

# GET http://localhost:5000/

GET http://localhost:5000/api/dashboard

# GET http://localhost:5000/api/

# POST http://localhost:5000/api/auth/login
# Content-Type: application/json

# {
#   "email": "sai@example.com",
#   "password": "123456"
# }
# # POST http://localhost:5000/api/auth/register
# # Content-Type: application/json

# {
#   "name": "Sai",
#   "email": "sai@example.com",
#   "password": "123456"
# }

# GET http://localhost:5000/api/auth/me

# POST  http://localhost:5000/api/auth/login

### Get current user
# GET http://localhost:5000/api/auth/me
# Authorization: Bearer {{token}}
# Authorization: Bearer abc123

# GET http://localhost:5000/api/auth/me

# POST http://localhost:5000/api/events
# Content-Type: application/json
# Authorization: Bearer {{token}}

# {
#   "title": "React Workshop",
#   "description": "Learn React from scratch",
#   "date": "2026-08-20",
#   "venue": "Seminar Hall",
#   "capacity": 100,
#   "image": ""
# }
